{% set name = "djangocms-frontend" %}
{% set version = "1.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/djangocms-frontend-{{ version }}.tar.gz
  sha256: a01fcb0a104739c2115ae7cf2e9607045618603118569744213041962b05b310

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - django >=2.2
    - django-cms >=3.7
    - django-filer >=1.7
    - easy-thumbnails
    - djangocms-attributes-field >=1
    - djangocms-text-ckeditor >=3.1.0
    - django-select2
    - django-entangled >=0.5.4

test:
  imports:
    - djangocms_frontend
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/django-cms/djangocms-frontend
  summary: Adds abstract User Interface items as plugins to django CMS.
  dev_url: https://github.com/django-cms/djangocms-frontend
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
